### ISSUE TITLE
Mistakes occurs when MCNP514 was compiled on Ubuntu 18.04LTS

### ISSUE THREAD

**Issue by ternence6** [ljacobson64/MCNP_CMake#2]
```
ternence@LAPTOP-CQSB53F7:~/MCNP/bld$
cmake ../src -DBUILD_MCNP514=ON\
>              -DBUILD_PLOT=ON\
>              -DCMAKE_INSTALL_PREFIX=$HOME/MCNP/bld\
>              -DBUILD_MPI=ON
```
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The Fortran compiler identification is GNU 7.5.0
-- Check for working Fortran compiler: /usr/bin/gfortran
-- Check for working Fortran compiler: /usr/bin/gfortran  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/bin/gfortran supports Fortran 90
-- Checking whether /usr/bin/gfortran supports Fortran 90 -- yes

-- CMAKE_BUILD_TYPE not specified, defaulting to Release
-- CMAKE_BUILD_TYPE: Release

-- Building shared executables
-- CMAKE_C_FLAGS:
-- CMAKE_CXX_FLAGS:
-- CMAKE_Fortran_FLAGS:
-- CMAKE_C_FLAGS_RELEASE: -O1
-- CMAKE_CXX_FLAGS_RELEASE: -O1
-- CMAKE_Fortran_FLAGS_RELEASE: -O1
-- CMAKE_C_IMPLICIT_LINK_LIBRARIES:
-- CMAKE_CXX_IMPLICIT_LINK_LIBRARIES: stdc++
-- CMAKE_Fortran_IMPLICIT_LINK_LIBRARIES:
-- CMAKE_EXE_LINKER_FLAGS:

-- MCNP514 source files found
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Found MPI_C: /usr/lib/libmpi.so (found version "3.1")
-- Found MPI_CXX: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so (found version "3.1")
-- Found MPI_Fortran: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_usempif08.so (found version "3.1")
-- Found MPI: TRUE (found version "3.1")
-- MCNP514 C_FLAGS:  -m64
-- MCNP514 CXX_FLAGS:
-- MCNP514 Fortran_FLAGS:  -m64 -mieee-fp -fdollar-ok -fno-sign-zero -fdefault-real-8
-- MCNP514 compile definitions: KODE="mcnp";THREAD="MCNP5_RSICC";TVERS="1.40";LODDAT="09/27/21";LINUX=ON;UNIX=ON;GFORTRAN=ON;F90_INT_4BYTE=ON;F90_REAL_8BYTE=ON;DPATH="/home/ternence/MCNP/MCNP_CMake/MCNPDATA";PLOT=ON;MCPLOT=ON;XLIB=ON;VERS="5.mpi";MULTP=ON;MPI=ON;DMMP_NAME="mcnp5.mpi";_DOTCOMM_MPI=ON
-- Building executable: mcnp514.mpi

-- Configuring done
-- Generating done
-- Build files have been written to: /home/ternence/MCNP/bld
`ternence@LAPTOP-CQSB53F7:~/MCNP/bld$ make -j9`
Scanning dependencies of target mcnp514.mpi
[  0%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/src/mcnp_params.F90.o
[  0%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/src/dynamic_arrays.F90.o
[  0%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/src/mcnp_debug.F90.o
[  1%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/src/mcnp_input.F90.o
[  1%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/src/pblcom.F90.o
[  2%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/src/mcnp_plot.F90.o
[  2%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/src/mcnp_landau.F90.o
[  2%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/dotcomm/src/dotcomm_const_mod.F90.o
[  2%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/src/mcnp_iofiles.F90.o
[  2%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/src/mcnp_data.F90.o
[  3%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/src/smmp.F90.o
[  3%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/src/mcnp_random.F90.o
[  4%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/dotcomm/src/dotcomm_abort.F90.o
[  4%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/dotcomm/src/dotcomm_allreduce.F90.o
[  4%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/src/lx5_mod.F90.o
[  4%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/dotcomm/src/dotcomm_barrier.F90.o
[  4%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/dotcomm/src/dotcomm_barrier_idle.F90.o
[  5%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/dotcomm/src/dotcomm_bcast.F90.o
[  5%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/dotcomm/src/dotcomm_check_process.F90.o
[  5%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/dotcomm/src/dotcomm_enroll.F90.o
[  6%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/dotcomm/src/dotcomm_get_numhosts.F90.o
[  6%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/dotcomm/src/dotcomm_get_numpes.F90.o
[  6%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/dotcomm/src/dotcomm_get_context.F90.o
[  6%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/dotcomm/src/dotcomm_get_penum.F90.o
[  7%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/dotcomm/src/dotcomm_init.F90.o
[  7%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/dotcomm/src/dotcomm_init_send.F90.o
[  8%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/dotcomm/src/dotcomm_msg_info.F90.o
[  8%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/dotcomm/src/dotcomm_pack.F90.o
[  8%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/dotcomm/src/dotcomm_pbcast.F90.o
[  9%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/dotcomm/src/dotcomm_precv.F90.o
[  9%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/dotcomm/src/dotcomm_probe.F90.o
[  9%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/dotcomm/src/dotcomm_psend.F90.o
[  9%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/dotcomm/src/dotcomm_recv.F90.o
[  9%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/dotcomm/src/dotcomm_reduce.F90.o
[  9%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/dotcomm/src/dotcomm_set_context.F90.o
[ 10%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/dotcomm/src/dotcomm_send.F90.o
[ 10%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/dotcomm/src/dotcomm_terminate.F90.o
[ 10%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/dotcomm/src/dotcomm_unpack.F90.o
[ 11%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/src/gkssim.F90.o
[ 11%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/dotcomm/src/dotcomm_mod.F90.o
[ 11%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/src/dmmp.F90.o
[ 11%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/src/ephcom.F90.o
[ 12%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/src/varcom.F90.o
[ 12%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/src/messages.F90.o
[ 12%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/src/fixcom.F90.o
[ 13%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/src/tskcom.F90.o
[ 13%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/src/mcnp_global.F90.o
[ 13%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/src/fmesh_mod.F90.o
[ 13%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/src/ra2_mod.F90.o
[ 13%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/src/rmc_mod.F90.o
[ 13%] Building Fortran object MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/src/gxsub.F90.o
/home/ternence/MCNP/src/MCNP514/Source/src/gxsub.F90:388:66:

         if( k==1 )  call gtx(real(a-w*i),real(ym+2.*t-ch),hn(1:i))
                                                                  1
Error: Type mismatch in argument ‘h’ at (1); passed CHARACTER(1) to REAL(8)
/home/ternence/MCNP/src/MCNP514/Source/src/gxsub.F90:389:63:

         if( k==2 )  call gtx(real(xm+2.*t),real(a-w*i),hn(1:i))
                                                               1
Error: Type mismatch in argument ‘h’ at (1); passed CHARACTER(1) to REAL(8)
/home/ternence/MCNP/src/MCNP514/Source/src/gxsub.F90:395:71:

         if(k == 1)call gtx(real(xx+6.*w),real(ym+2.*t-ch),'e'//hn(1:i))
                                                                       1
Error: Type mismatch in argument ‘h’ at (1); passed CHARACTER(1) to REAL(8)
/home/ternence/MCNP/src/MCNP514/Source/src/gxsub.F90:396:71:

         if(k == 2)call gtx(real(xm+2.5*t-ch),real(yx-i*w),'e'//hn(1:i))
                                                                       1
Error: Type mismatch in argument ‘h’ at (1); passed CHARACTER(1) to REAL(8)
/home/ternence/MCNP/src/MCNP514/Source/src/gxsub.F90:435:66:

         if( k==1 )  call gtx(real(i-w*j),real(ym+2.*t-ch),hn(1:j))
                                                                  1
Error: Type mismatch in argument ‘h’ at (1); passed CHARACTER(1) to REAL(8)
/home/ternence/MCNP/src/MCNP514/Source/src/gxsub.F90:436:63:

         if( k==2 )  call gtx(real(xm+2.*t),real(i-w*j),hn(1:j))
                                                               1
Error: Type mismatch in argument ‘h’ at (1); passed CHARACTER(1) to REAL(8)
/home/ternence/MCNP/src/MCNP514/Source/src/gxsub.F90:450:76:

       if( k==1 )  call gtx(real(.5*(xm+xx)-w*j),real(ym+2.5*t-a*ch),hl(1:j))
                                                                            1
Error: Type mismatch in argument ‘h’ at (1); passed CHARACTER(1) to REAL(8)
/home/ternence/MCNP/src/MCNP514/Source/src/gxsub.F90:451:78:

       if( k==2 )  call gtx(real(xm+2.5*t-1.2*ch),real(.5*(ym+yx)-w*j),hl(1:j))
                                                                              1
Error: Type mismatch in argument ‘h’ at (1); passed CHARACTER(1) to REAL(8)
/home/ternence/MCNP/src/MCNP514/Source/src/gxsub.F90:181:21:

     call gtx(s,t,'.')
                     1
Error: Type mismatch in argument ‘h’ at (1); passed CHARACTER(1) to REAL(8)
MCNP514/CMakeFiles/mcnp514.mpi.dir/build.make:2654: recipe for target 'MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/src/gxsub.F90.o' failed
make[3]: *** [MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/src/gxsub.F90.o] Error 1
MCNP514/CMakeFiles/mcnp514.mpi.dir/build.make:2670: recipe for target 'MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/src/gxsub.F90.o.provides' failed
make[2]: *** [MCNP514/CMakeFiles/mcnp514.mpi.dir/Source/src/gxsub.F90.o.provides] Error 2
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:85: recipe for target 'MCNP514/CMakeFiles/mcnp514.mpi.dir/all' failed
make[1]: *** [MCNP514/CMakeFiles/mcnp514.mpi.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ternence6** [comment]
This is my fortran version

```
ternence@LAPTOP-CQSB53F7:~/MCNP/bld$ gfortran --version
GNU Fortran (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
I guess maybe it is because the version of fortran on 18.04LTS is too higher?

**Comment by ljacobson64** [comment]
Hi @ternence6,

I cannot reproduce your error on Ubuntu 18.04. I looked into it and it appears that my MCNP 5.1.4 source code is different from yours for `gxsub.F90`. Your errors appeared in lines 181, 388, 389, 395, 396, 435, 436, 450, and 451. However my version of `gxsub.F90` only has 412 lines for all versions of MCNP5 (5.1.4, 5.1.5, and 5.1.6).

**Comment by ternence6** [comment]
> Hi @ternence6,
> 
> I cannot reproduce your error on Ubuntu 18.04. I looked into it and it appears that my MCNP 5.1.4 source code is different from yours for `gxsub.F90`. Your errors appeared in lines 181, 388, 389, 395, 396, 435, 436, 450, and 451. However my version of `gxsub.F90` only has 412 lines for all versions of MCNP5 (5.1.4, 5.1.5, and 5.1.6).

Ty for your reply.I would check my Source files again.Maybe it did be the gxsub.F90 error.
:)

**Comment by ternence6** [comment]
This is my gxsub.F90,does there exist any different word?
```
!+ $Id$
! Copyright LANL/UC/DOE - see file COPYRIGHT_INFO

module gxsub
  ! Description:
  ! Routines needed to initialize windows, colors, control terminals, etc.
  ! Includes gxon, gxoff, gxhome, gxskip, gxquit, gxlims, gxaxis
  ! Modules used:
  use mcnp_global
  use mcnp_debug
  use gkssim

  implicit none

  private
  public :: gxon, gxoff, gxhome, gxskip, gxquit, gxlims, gxaxis

#if !defined(PLOT) && !defined(MCPLOT)
contains
  ! Dummy interfaces.
  subroutine gxon(nw)
    integer :: nw
    return
  end subroutine gxon
  subroutine gxoff
    integer :: nw
    return
  end subroutine gxoff
  subroutine gxhome(s,t)
    real :: s,t
    return
  end subroutine gxhome
  subroutine gxskip
    return
  end subroutine gxskip
  subroutine gxquit
    return
  end subroutine gxquit
  subroutine gxlims(a,b,ap,bp,np,jf)
    real(dknd) :: a,b,ap,bp
    integer    :: np, jf
    return
  end subroutine gxlims
  subroutine gxaxis(xm,xx,ym,yx,t,zg,ni,jf,kn,hl)
    real             :: xm, xx, ym, yx, t, zg
    integer          :: ni, jf, kn
    character(len=*) :: hl
    return
  end subroutine gxaxis

#else

contains

  !--------------------------------------------------------------------------
  ! Actual routines.

  subroutine gxon(nw)
    ! Description:
    ! Turn on workstation nw.  nw=1 for terminal, 2 for metafile.

    ! Modules used:
    use mcnp_plot
#ifdef LAHEY
    use WINTERACTER
    type (win_style) :: MCNPwin
#endif
    integer :: nw
    integer :: kn(2),ic,ni,i,jt,ie,nc
    character(len=12) :: hf

    kn(1) = jtty
    kn(2) = iup

    if( jgxa(nw)==0 ) then
      if( jgxo(nw)==0 ) then
        ! Open gks if it has not already been done.
        if( jgxo(3-nw)==0 )  call gopks

        ! Open workstation nw.
        if( nw==1 )  jt = iterm
        if( nw==2 )  jt = 1
        hf=plotm(1:len_trim(plotm))//'.ps'
        if( nw==2 )  call unique(hf,jtty)
        if(nw == 2)open(iup+50,file=hf,status='unknown')
        call gopwk(nw,kn(nw),jt)
        if( kn(nw)<0 )  return
        jgxo(nw) = 1

        ! Check for a color display and initialize color indices.
        ! If terminal and metafile output devices are used, the terminal
        ! color status is applied to metafiles.  If only a metafile
        ! device is used, the default color status is on.
        if( nw/=2 .or. jgxo(1)==0 ) then
          ic = 1
          ni = ncolor
          if( nw==1 )  call gqcf(ic,ni)
          if( ic/=0 .and. ni>2 ) then
            mcolor = sign(min(ni,ncolor),mcolor)
            do i = 1,ncolor+7
#if defined(LAHEY) || defined(QWIN)
              if( i<=ncolor )  kcolor(i) = i
              if( i<=7 )  kcolor(ncolor+i) = i
              if( ni<ncolor+7 )  cycle
#endif
              kcolor(i) = abs(kci(i))
              colors(i)%rgb(1) = nint(255*colors(i)%r)
              colors(i)%rgb(2) = nint(255*colors(i)%g)
              colors(i)%rgb(3) = nint(255*colors(i)%b)
            enddo
            call set_shades
          endif
        endif
      endif

      ! Activate workstation nw.
      call gacwk(nw)
      jgxa(nw) = 1
      if( nw==1 )  call gclrwk(1,1)
    endif

    ! Set the workstation window and the viewport.
    if( nw/=1 .or. iterm/=4 )  call gswkwn(nw,0.,1.,0.,.75+jvp*.25)
    call gsvp(1,0.,1.,0.,.75+jvp*.25)
    wnvp(3) = 1.
    wnvp(4) = .75+jvp*.25
#ifdef LAHEY
    if( nw==1 ) then
      call WInitialise(' ')
      MCNPwin%flags = MinButton + MaxButton
      MCNPwin%x = 0
      MCNPwin%y = 0
      MCNPwin%width = 0
      MCNPwin%height = 0
      MCNPwin%menuid = 0
      MCNPwin%title = "MCNP Plot Window"
      call WindowOpen(MCNPwin)
      call IGrArea(0.0,0.0,1.0,1.0)
      call IGrUnits(0.0,0.0,11.0,8.5)
    endif
#endif
    return
  end subroutine gxon

  !--------------------------------------------------------------------------

  subroutine gxoff(nw)
    ! Description:
    ! Turn off workstation nw.

    integer :: nw

    if( jgxa(nw)==0 )  return
    call gdawk(nw)
    jgxa(nw) = 0
    return
  end subroutine gxoff

  !--------------------------------------------------------------------------

  subroutine gxhome(s,t)
    ! Description:
    ! Return home, update the display, and be ready for fortran i/o.

    ! Modules used
#ifdef LAHEY
    use WINTERACTER
#endif

    real :: s,t
#ifdef LAHEY
    integer           :: ia(9)
    real              :: ra(7), t1, t2
    character(len=40) :: hl
#endif

    if( jgxa(1)==0 )  return
    call gschh(.01*real(wnvp(2)))

#ifndef LAHEY
    call gtx(s,t,'.')

#else
    !* seems to be a 4 sec pause for LAHEY only.
    call secnd(t1)
    if( ifile/=itty ) then
      do
        call secnd(t2)
        if( t2-t1>=4.d0 )  exit
      enddo
    endif
#endif
    call guwk(1,0)
    return
  end subroutine gxhome

  !--------------------------------------------------------------------------

  subroutine gxskip
    ! Description:
    ! Clear the terminal display and/or advance to the next frame.

    integer :: i
    do i = 1,2
      if( jgxa(i)/=0 )  call gclrwk(i,1)
      if( jgxa(i)/=0 )  call guwk(i,1)
    enddo
    return
  end subroutine gxskip

  !--------------------------------------------------------------------------

  subroutine gxquit
    ! Description:
    ! Shut down all graphics.

    if( jgxa(1)/=0 )  call gdawk(1)
    if( jgxa(2)/=0 )  call gdawk(2)
    if( jgxo(1)/=0 )  call gclwk(1)
    if( jgxo(2)/=0 )  call gclwk(2)
    jgxa(1) = 0
    jgxa(2) = 0
    jgxo(1) = 0
    jgxo(2) = 0
    return
  end subroutine gxquit

  !--------------------------------------------------------------------------

  subroutine gxlims(a,b,ap,bp,np,jf)
    ! Description:
    ! Define axis limits ap and bp to cover the range from a to b.
    ! b>a is required.  jf=0 for a linear axis, otherwise log10.
    ! If linear, also define the number of divisions np in the range
    ! from 4 to 8.  The increment per division will be 1, 2, or 5.
    ! If log10, ap and bp will be powers of 10.

    ! Arguments:
    real(dknd) :: a,b,ap,bp
    integer    :: np, jf
    ! Locals:
    real(dknd) :: ai,bi,e,f,g
    integer    :: i,j

    if( jf==0 ) then
      ! Linear case.
      e = log10((b-a)/3.99)
      i = e
      if( e<0.)  i = i-1
      f = 10.**i
      g = 2.
      do
        ai = a/f
        bi = b/f
        i = ai
        if( ai<0. .and. i/=ai )  i = i-1
        j = bi
        if( bi>0. .and. j/=bi )  j = j+1
        np = j-i
        if( np<=8) exit
        f = f*g
        g = g+.5
      enddo
      ap = i*f
      bp = j*f
      return
    else
      ! Log10 case.
      i = log10(a)
      if( a<1.)  i = i-1
      j = log10(b)
      if( b>1.)  j = j+1
      ap = 10.**max(i,j-17)
      bp = 10.**j
    endif

    return
  end subroutine gxlims

  !--------------------------------------------------------------------------

  subroutine gxaxis(xm,xx,ym,yx,t,zg,ni,jf,kn,hl)
    ! Description:
    ! Draw an axis from xm,ym to xx,yx.  either xm=xx or ym=yx.
    ! Add tick marks of length and direction t.
    ! Extend ticks as grid lines to zg.  no grid if zg=0.
    !  jf=0 for linear (do ni intervals), otherwise log10.
    ! Provide nice intervals if jf=0 and ni=0.
    !  kn=0 for no numbers, otherwise numbers.
    !  hl = the axis label.

    real             :: xm, xx, ym, yx, t, zg
    integer          :: ni, jf, kn
    character(len=*) :: hl

    character  ::  hn*10, hp(7)*5
    real       :: xy(2,2),cr(9),zt(2,2)
    integer    :: i,j,k,kf,l,m,n,np
    real(dknd) :: a,b,ap,bp,c,ch,d,e,f,u,v,w,x,xl,xu,dx
    data cr/1500.,45.,18.,60.,12.,27.,9.,15.,7.5/
    data hp/'0.001','0.01','0.1','1.','10.','100.','1000.'/

    xy(1,1) = xm
    xy(2,1) = xx
    xy(1,2) = ym
    xy(2,2) = yx
    call gpl(2,xy(1,1),xy(1,2))
    if( t==0. .and. zg==0. )  return
    k = 1
    if( xm==xx )  k = 2
    zt(2,3-k) = xy(1,3-k)+t
    ch = .017*wnvp(3-k)*wnvp(2+k)
    w = .0064*wnvp(k)*wnvp(5-k)

    if( jf==0 ) then
      ! Add ticks and/or grid lines to linear axis.
      ap = xy(1,k)
      bp = xy(2,k)
      np = ni
      if( ni==0 ) then
        a = ap
        b = bp
        call gxlims(a,b,ap,bp,np,0)
      endif
      d = (bp-ap)/np
      zt(1,3-k) = xy(1,3-k)+zg
      u = xy(1,k)-.0003*(xy(2,k)-xy(1,k))
      v = xy(2,k)+.0003*(xy(2,k)-xy(1,k))
      do i = 1,np+1
        zt(1,k) = ap+d*(i-1)
        zt(2,k) = zt(1,k)
        if( zt(1,k)>v )  exit
        if( zt(1,k)>=u )  call gpl(2,zt(1,1),zt(1,2))
      enddo

      ! Add minor ticks.
      if( ni==0 ) then
        zt(1,3-k) = xy(1,3-k)
        zt(2,3-k) = xy(1,3-k)+.5*t
        m = 10
        if( np>6 )  m = 5
        e = d/m
        OLIN: do i = 1,np
          a = ap+d*(i-1)
          do j = 1,m-1
            zt(1,k) = a+e*j
            zt(2,k) = zt(1,k)
            if( zt(1,k)>v) exit OLIN
            if( zt(1,k)>=u )  call gpl(2,zt(1,1),zt(1,2))
          enddo
        enddo OLIN
      endif

      ! Print numbers on linear axis.
      if( kn==0 )  return
      if( k==2 )  call gschup(-1.,0.)
      call gschh(.8*real(ch))
      kf = 3
      a = max(abs(ap),abs(bp))
      c = 1.
      if( min(ap,bp)<0.)  c = .1
      if( a<=9999.*c .and. a>=.1 )  kf = 2
      j = bp-ap
      if( a<=99999.*c .and. aint(ap)==ap .and. aint(bp)==bp .and. &
        & np*(j/np)==j )  kf = 1
      j = log10(a)
      if( a<1. .and. a/=10.**j )  j = j-1
      f = 1./10.**j
      do l = 1,np+1
        a = ap+(l-1)*d
        if( a>v )  exit
        if( a<u )  cycle
        select case (kf)
        case (1)
          write(hn,'(i6)')nint(a)
        case (2)
          write(hn,'(f10.4)')a
        case(3)
          write(hn,'(f10.3)')a*f
        end select
        do i = 1,4
          if(hn(11-i:11-i) /= '0') exit
          hn(11-i:11-i)=' '
        enddo
        hn = adjustl(hn)
        hn(6:10)=' '
        i = len_trim(hn)
        if( k==1 )  call gtx(real(a-w*i),real(ym+2.*t-ch),hn(1:i))
        if( k==2 )  call gtx(real(xm+2.*t),real(a-w*i),hn(1:i))
      enddo
      if( kf==3 .and. j/=0 ) then
        write(hn,'(i3)')j
        hn = adjustl(hn)
        i = len_trim(hn)
        if(k == 1)call gtx(real(xx+6.*w),real(ym+2.*t-ch),'e'//hn(1:i))
        if(k == 2)call gtx(real(xm+2.5*t-ch),real(yx-i*w),'e'//hn(1:i))
      endif

    else
      ! Add ticks to log10 axis.
      m = xy(1,k)
      if( xy(1,k)<0. .and. m/=xy(1,k))  m = m-1
      n = xy(2,k)
      if( xy(2,k)>0. .and. n/=xy(2,k))  n = n+1
      d = xy(2,k)-xy(1,k)
      x = 10.**m
      xl = 10.**xy(1,k)
      xu = 10.**xy(2,k)
      OLOG: do i = 1,n-m+1
        dx = x
        do j = 1,9
          if( x>xu*(1.+.001*d))  exit OLOG
          if( x>=xl*(1.-.001*d) .and. cr(j)>=d ) then
            zt(1,3-k) = xy(1,3-k)
            if( j==1 )  zt(1,3-k) = xy(1,3-k)+zg
            zt(1,k) = log10(x)
            zt(2,k) = zt(1,k)
            call gpl(2,zt(1,1),zt(1,2))
          endif
          x = x+dx
        enddo
      enddo OLOG

      ! Print numbers on log10 axis.
      if( kn==0 )  return
      if( k==2 )  call gschup(-1.,0.)
      call gschh(.8*real(ch))
      do i = m,n
        if( i>xy(2,k)+.001*d )  exit
        if( i<xy(1,k)-.001*d )  cycle
        write(hn,'( "10",sp,i4)')i
        hn(3:10) = adjustl(hn(3:10))
        if( i>=-3 .and. i<=3 )  hn = hp(i+4)
        j = len_trim(hn)
        if( k==1 )  call gtx(real(i-w*j),real(ym+2.*t-ch),hn(1:j))
        if( k==2 )  call gtx(real(xm+2.*t),real(i-w*j),hn(1:j))
      enddo
    endif ! Log10 axis.

    ! Print the axis label, if any.
    if(hl /= ' ')then
      j = len_trim(hl)
      call gschh(real(ch))
      w = 1.25*w
#ifdef XLIB
      a = 2.2
#else
      a = 3.0
#endif
      if( k==1 )  call gtx(real(.5*(xm+xx)-w*j),real(ym+2.5*t-a*ch),hl(1:j))
      if( k==2 )  call gtx(real(xm+2.5*t-1.2*ch),real(.5*(ym+yx)-w*j),hl(1:j))
    endif
    if( k==2 )  call gschup(0.,1.)
    return
  end subroutine gxaxis
#endif
end module gxsub

```

**Comment by ljacobson64** [comment]
I deleted your comment since I don't think it's a good idea to post full MCNP source code files for anyone to read on the internet. But I looked at it and did see that it was different from mine. Can you post the first few lines of the `gtx` function in your version of `gkssim.F90`? Mine looks like this:
```
  subroutine gtx(x,y,h)
    ! perform gks function 'text'.

    character(len=*) :: h
    real             :: x,y
    character(len=120) :: hn
    integer :: ns = 0
#ifdef AIX
    integer*4 n
#else
    integer   n
#endif
```

**Comment by ternence6** [comment]
> I deleted your comment since I don't think it's a good idea to post full MCNP source code files for anyone to read on the internet. But I looked at it and did see that it was different from mine. Can you post the first few lines of the `gtx` function in your version of `gkssim.F90`? Mine looks like this:
> 
> ```
>   subroutine gtx(x,y,h)
>     ! perform gks function 'text'.
> 
>     character(len=*) :: h
>     real             :: x,y
>     character(len=120) :: hn
>     integer :: ns = 0
> #ifdef AIX
>     integer*4 n
> #else
>     integer   n
> #endif
> ```
```
subroutine gtx(x,y,h)
    ! perform gks function 'text'.

#ifdef LAHEY
    use WINTERACTER
#endif /*def.lahey*/
#ifdef QWIN
    use dflib
    type (wxycoord) xy
#endif /*def.qwin*/
    character(len=*) :: h
    real             :: x,y
    character(len=120) :: hn
    integer :: ns = 0
#ifdef AIX
    integer*4 n
#else
    integer   n
#endif

```

**Comment by ljacobson64** [comment]
Hmm, your version is functionally the same as mine. Those preprocessor directives shouldn't change anything. Your error messages all indicate that you are trying to pass a `CHARACTER(1)` to a `REAL(8)` in the 3rd argument of the `gtx` subroutine, but both of our `gtx` subroutines clearly show that the 3rd argument is a character, not a real. I have no idea what would be causing this issue.

**Comment by ternence6** [comment]
> Hmm, your version is functionally the same as mine. Those preprocessor directives shouldn't change anything. Your error messages all indicate that you are trying to pass a `CHARACTER(1)` to a `REAL(8)` in the 3rd argument of the `gtx` subroutine, but both of our `gtx` subroutines clearly show that the 3rd argument is a character, not a real. I have no idea what would be causing this issue.

yes，that is the reason why I feel so confused.could you tell me your directory structure about MCNP514？

**Comment by ljacobson64** [comment]
I'm not sure what you mean

**Comment by ternence6** [comment]
> I'm not sure what you mean

Ty for your reply.In the beginning,I thought there exist something wrong with my directory structure,which is the reason why I said that.While the error,I guessed,had nothing to do with the directory structure.
